name: gmaps_picker
description: A flutter widget to pick a location from Google Map.
version: 1.0.1
homepage: https://github.com/pepsighan/gmaps_picker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^1.0.10
  geolocator: ^6.1.13

dev_dependencies:
  pedantic: ^1.9.2
